### ISSUE TITLE
Integration stops after update HA to 2023.6.1

### ISSUE THREAD

**Issue by anthonywalker75** [asantaga/lightwaverf_HA_EnergySensor#15]
Hello

I recently upgraded my HA to 2023.6.1 and the energy monitor integration seems to have stopped working.

Log entry below:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/lightwaverf_energy/sensor.py:55
Integration: Lightwave Energy Monitor
First occurred: 00:37:13 (58 occurrences)
Last logged: 00:51:13

Update for sensor.electricity_current_usage_w fails
Update for sensor.electricity_energy_today_usage_kwh fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lightwaverf_energy/sensor.py", line 55, in update
    sock.bind(("0.0.0.0", 9761))
OSError: [Errno 98] Address in use

It was working prior to the upgrade. Any ideas?

Anthony

**Comment by asantaga** [comment]
mmm Ive seen this before and then it just disappeared. Im away from home but i'll be upgrading mine early nextweek, maybe the latest version of HA has broken it.. :-(

**Comment by smeg1** [comment]
Same here

**Comment by Ashk0812** [comment]
Is this still a thing? mines not updating at all

**Comment by asantaga** [comment]
Sorry, Ive been busy at work and renovating the house. I will look at it asap.

But im not sure whats going on here.. ..

**Comment by Ashk0812** [comment]
I did restore my HA to a earlier version 5.4  and it started to work again so it is something related to the update

**Comment by asantaga** [comment]
Sigh.... i think its to do with the networking... threading

**Comment by asantaga** [comment]
ok, Ive done some debugging, and yes, its because the network model has chnaged since i wrote this.

I need to reimplement it as a async call.... 

I'll try and do this asap

**Comment by dgilbert2** [comment]
Just tried this on a new 2026.1.1 without success and was wondering if this issue was resolved?

**Comment by asantaga** [comment]
it now works, i finally got around to looking at it. Its fixed in a beta release, Im testing a newer version which is a bit of a rewrite to make it async
