### ISSUE TITLE
New component model doesnt respect default values

### ISSUE THREAD

**Issue by asantaga** [asantaga/lightwaverf_HA_EnergySensor#4]
Branch : MigrateComponnetToNewModel
No idea why the default valuing isnt working for ```scan_interval``` . If not supplied you get a key error

**Comment by matthewjporter** [comment]
I currently have it set in my confiuration file, will remove and test if it still updates

**Comment by bluntiless** [comment]
Hi and thanks for your code! However can you advise what I need to do to get this set up. I am getting this error:



2019-10-13 14:08:36 ERROR (MainThread) [homeassistant.setup] Error during setup of component lightwaverf_energy
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/lightwaverf_energy/__init__.py", line 26, in setup
    hass.data[DATA_KEY] = config[DOMAIN][0][CONF_SCAN_INTERVAL]
IndexError: list index out of range.

Not sure what to do from here?
